import "server-only"

// Phase 11 WS-C.4 — WebAuthn helpers. v9 of @simplewebauthn/server
// is constrained by next-auth v4 (peerOptional @auth/core 0.34.3).
// The protocol-level API is essentially identical to v10/v11 for our
// purposes.

/** Relying-party identity. RP ID must be the registrable domain
 *  (without scheme or port) for production; for local dev we accept
 *  localhost. Origin is the full URL including scheme. */
export function getRpConfig(): { rpID: string; rpName: string; origin: string } {
  const publicUrl =
    process.env.FLEETHUB_PUBLIC_URL?.trim() || "https://fleethub.pcc2k.com"
  const u = new URL(publicUrl)
  return {
    rpID: u.hostname,
    rpName: "FleetHub",
    origin: u.origin,
  }
}

/** WebAuthn challenges are stateful — generated by /options, posted
 *  back during /verify. We persist the per-flow challenge in an
 *  HTTP-only cookie keyed by purpose ('register' | 'authenticate').
 *  Cookie value is just the challenge string (base64url) — the
 *  cookie's httpOnly + secure flag is the integrity boundary. TTL is
 *  short (5 minutes — operator picks up phone, taps yubikey, done). */
export const WEBAUTHN_CHALLENGE_COOKIE_PREFIX = "fleethub_webauthn_chal_"
export const WEBAUTHN_CHALLENGE_TTL_SECONDS = 300
