import "server-only"
import { prisma } from "@/lib/prisma"

// PHASE-5-DESIGN §3.5: Quarterly Business Review.
//
// Executive rollup. Audience defaults to "client"; tech adds drill-down.
// The cover-page narrative is generated separately (lib/ai/qbr-narrative.ts)
// from this same structured shape — keep the data assembly pure so the
// narrative is always re-derivable from the same inputs (per §10).
//
// Window semantics: defaults to the last full calendar quarter when no
// explicit range is supplied. Operators can override with startDate /
// endDate on the report row.

const KEV_TOP_N = 10
const EOL_TOP_N = 12
const TOP_RESOLVED_ALERTS = 8
const TOP_DEPLOYS = 6

export interface QbrData {
  tenantName: string
  startDate: Date
  endDate: Date
  audience: "tech" | "client" | "auditor"

  /** Period label like "Q1 2026" or "2026-04-01 - 2026-06-30". */
  periodLabel: string

  /** When set, embedded on the cover page. Generated by qbr-narrative.ts. */
  narrative: string | null

  headline: {
    hostsManaged: number
    patchesApplied: number       // Fl_PatchInstall installed within window
    scriptsExecuted: number      // Fl_ScriptRun.state=ok in window
    alertsResolved: number       // Fl_Alert.resolvedAt in window
    deploysCompleted: number     // Fl_Deployment.status=completed in window
    /** Hosts on which at least one approved patch is still missing as of endDate. */
    hostsWithOpenPatches: number
  }

  /** Top resolved alerts in window — for the "Wins" section. */
  wins: Array<{
    title: string
    severity: string
    resolvedAt: Date
    durationDays: number   // createdAt -> resolvedAt
    hostname: string | null
  }>

  /** Notable completed deployments. */
  notableDeploys: Array<{
    packageName: string
    completedAt: Date
    succeeded: number
    failed: number
    totalTargets: number
  }>

  /** Risks: KEV CVEs still missing on hosts, EOL hardware, identity gaps. */
  risks: {
    /** Unpatched KEV CVEs still present on at least one host as of endDate. */
    kevExposure: Array<{
      cveId: string
      cvssBase: number | null
      affectedHosts: number
      patchSourceId: string  // KB / vendor advisory id
    }>
    eolHosts: Array<{
      hostname: string
      clientName: string
      reason: string
    }>
    /** Populated only when Fl_Tenant.scoutTenantId is set; else empty. */
    identityGaps: Array<{
      label: string
      detail: string
    }>
  }

  /** Looking ahead: pending/queued deploys + lifecycle items. */
  lookingAhead: Array<{
    label: string
    detail: string
  }>
}

export async function buildQbrReport(input: {
  tenantName: string
  startDate?: Date
  endDate?: Date
  audience?: "tech" | "client" | "auditor"
}): Promise<Omit<QbrData, "narrative">> {
  const audience = input.audience ?? "client"
  const { startDate, endDate, periodLabel } = resolveQuarter(input.startDate, input.endDate)

  // Tenant: total managed hosts.
  const devices = await prisma.fl_Device.findMany({
    where: { clientName: input.tenantName, isActive: true },
    select: { id: true, hostname: true, clientName: true, os: true, osVersion: true, inventoryJson: true },
  })
  const deviceById = new Map(devices.map((d) => [d.id, d]))
  const deviceIds = devices.map((d) => d.id)

  // Headline counts in window.
  const [
    patchesApplied,
    scriptsExecuted,
    alertsResolved,
    deploysCompletedRows,
  ] = await Promise.all([
    prisma.fl_PatchInstall.count({
      where: {
        deviceId: { in: deviceIds },
        state: "installed",
        installedAt: { gte: startDate, lte: endDate },
      },
    }),
    prisma.fl_ScriptRun.count({
      where: {
        deviceId: { in: deviceIds },
        state: "ok",
        finishedAt: { gte: startDate, lte: endDate },
      },
    }),
    prisma.fl_Alert.count({
      where: {
        clientName: input.tenantName,
        state: "resolved",
        resolvedAt: { gte: startDate, lte: endDate },
      },
    }),
    prisma.fl_Deployment.findMany({
      where: {
        tenantName: input.tenantName,
        status: "completed",
        completedAt: { gte: startDate, lte: endDate },
      },
      include: { package: { select: { name: true } } },
      orderBy: { completedAt: "desc" },
    }),
  ])

  // Hosts with at least one approved missing patch as of endDate.
  const openPatchRows = await prisma.fl_PatchInstall.findMany({
    where: {
      deviceId: { in: deviceIds },
      state: { in: ["missing", "failed", "preflight-failed"] },
      lastDetectedAt: { lte: endDate },
      patch: { is: { approvalState: "approved" } },
    },
    select: { deviceId: true },
  })
  const hostsWithOpenPatches = new Set(openPatchRows.map((r) => r.deviceId)).size

  // Wins — top resolved alerts by severity, then most-recent.
  const resolvedAlerts = await prisma.fl_Alert.findMany({
    where: {
      clientName: input.tenantName,
      state: "resolved",
      resolvedAt: { gte: startDate, lte: endDate },
    },
    orderBy: [{ severity: "desc" }, { resolvedAt: "desc" }],
    take: TOP_RESOLVED_ALERTS * 4,  // over-fetch then sort by our band priority
  })
  const sevRank: Record<string, number> = { critical: 0, warn: 1, info: 2 }
  const wins = resolvedAlerts
    .filter((a) => a.resolvedAt != null)
    .sort((a, b) => (sevRank[a.severity] ?? 9) - (sevRank[b.severity] ?? 9))
    .slice(0, TOP_RESOLVED_ALERTS)
    .map((a) => ({
      title: a.title,
      severity: a.severity,
      resolvedAt: a.resolvedAt!,
      durationDays: Math.max(
        0,
        Math.floor((a.resolvedAt!.getTime() - a.createdAt.getTime()) / 86_400_000),
      ),
      hostname: a.deviceId ? (deviceById.get(a.deviceId)?.hostname ?? null) : null,
    }))

  // Notable deploys — biggest completed in window by total targets.
  const notableDeploys = deploysCompletedRows
    .sort((a, b) => b.totalTargets - a.totalTargets)
    .slice(0, TOP_DEPLOYS)
    .map((d) => ({
      packageName: d.package.name,
      completedAt: d.completedAt!,
      succeeded: d.succeededCount,
      failed: d.failedCount,
      totalTargets: d.totalTargets,
    }))

  // Risk: KEV exposure — patches with isKev=true still missing on >=1 host.
  const missingPatchInstalls = await prisma.fl_PatchInstall.findMany({
    where: {
      deviceId: { in: deviceIds },
      state: { in: ["missing", "failed", "preflight-failed"] },
      patch: { is: { approvalState: "approved", isKev: true } },
    },
    include: {
      patch: { select: { sourceId: true, cveJson: true, cvssMax: true } },
    },
  })
  const kevByCve = new Map<string, { cveId: string; cvssBase: number | null; hosts: Set<string>; sourceId: string }>()
  for (const i of missingPatchInstalls) {
    let cveIds: string[] = []
    try { cveIds = JSON.parse(i.patch.cveJson ?? "[]") } catch { cveIds = [] }
    if (cveIds.length === 0) cveIds = [i.patch.sourceId]
    for (const cve of cveIds) {
      const cur = kevByCve.get(cve) ?? {
        cveId: cve,
        cvssBase: i.patch.cvssMax,
        hosts: new Set<string>(),
        sourceId: i.patch.sourceId,
      }
      cur.hosts.add(i.deviceId)
      kevByCve.set(cve, cur)
    }
  }
  const kevExposure = Array.from(kevByCve.values())
    .map((k) => ({
      cveId: k.cveId,
      cvssBase: k.cvssBase,
      affectedHosts: k.hosts.size,
      patchSourceId: k.sourceId,
    }))
    .sort((a, b) => (b.cvssBase ?? 0) - (a.cvssBase ?? 0) || b.affectedHosts - a.affectedHosts)
    .slice(0, KEV_TOP_N)

  // Risk: EOL hosts (hardware >4y or known-EOL OS strings).
  const eolHosts: QbrData["risks"]["eolHosts"] = []
  for (const d of devices) {
    let purchaseDate: string | null = null
    let osText: string | null = null
    try {
      if (d.inventoryJson) {
        const inv = JSON.parse(d.inventoryJson) as {
          hardware?: { purchaseDate?: string }
          os?: { version?: string }
        }
        purchaseDate = inv.hardware?.purchaseDate ?? null
        osText = inv.os?.version ?? null
      }
    } catch { /* swallow */ }
    osText = osText ?? d.osVersion
    const reasons: string[] = []
    if (purchaseDate) {
      const ageYears = (endDate.getTime() - new Date(purchaseDate).getTime()) / (365 * 86_400_000)
      if (Number.isFinite(ageYears) && ageYears >= 4) {
        reasons.push(`hardware ${ageYears.toFixed(1)}y old`)
      }
    }
    if (osText) {
      if (/Windows 10/i.test(osText)) reasons.push("Windows 10 EOL 2025-10-14")
      if (/Server 2012 R2/i.test(osText)) reasons.push("Server 2012 R2 EOL 2023-10-10")
      if (/Server 2016/i.test(osText)) reasons.push("Server 2016 mainstream end")
    }
    if (reasons.length > 0) {
      eolHosts.push({
        hostname: d.hostname,
        clientName: d.clientName,
        reason: reasons.join(", "),
      })
    }
  }
  eolHosts.splice(EOL_TOP_N)

  // Risk: identity gaps. Phase 5.5 cross-app pull from Scout — for now,
  // emit a placeholder when the binding is missing so the report is honest.
  const tenant = await prisma.fl_Tenant.findUnique({
    where: { name: input.tenantName },
    select: { scoutTenantId: true },
  })
  const identityGaps: QbrData["risks"]["identityGaps"] = []
  if (!tenant?.scoutTenantId && audience !== "client") {
    identityGaps.push({
      label: "M365 audit not bound",
      detail: "No Scout tenant linked. Run an Identity Posture audit in Scout and bind via Fl_Tenant.scoutTenantId.",
    })
  }

  // Looking ahead — queued/pending deploys + KEV exposure + EOL count.
  const queuedDeploys = await prisma.fl_Deployment.findMany({
    where: {
      tenantName: input.tenantName,
      status: { in: ["queued", "running", "paused"] },
    },
    include: { package: { select: { name: true } } },
    orderBy: { scheduledFor: "asc" },
    take: 5,
  })
  const lookingAhead: QbrData["lookingAhead"] = []
  for (const d of queuedDeploys) {
    const when = d.scheduledFor ? d.scheduledFor.toISOString().slice(0, 10) : "unscheduled"
    lookingAhead.push({
      label: `Deploy ${d.package.name}`,
      detail: `${d.totalTargets} target(s), ${d.status}, ${when}`,
    })
  }
  if (kevExposure.length > 0) {
    const totalAffected = kevExposure.reduce((acc, k) => acc + k.affectedHosts, 0)
    lookingAhead.push({
      label: "KEV remediation",
      detail: `${kevExposure.length} unpatched KEV CVE(s) across ${totalAffected} host-pairing(s) - recommend prioritizing this quarter`,
    })
  }
  if (eolHosts.length > 0) {
    lookingAhead.push({
      label: "Lifecycle replacements",
      detail: `${eolHosts.length} host(s) flagged for hardware or OS EOL - budget conversation in next QBR`,
    })
  }

  return {
    tenantName: input.tenantName,
    startDate,
    endDate,
    audience,
    periodLabel,
    headline: {
      hostsManaged: devices.length,
      patchesApplied,
      scriptsExecuted,
      alertsResolved,
      deploysCompleted: deploysCompletedRows.length,
      hostsWithOpenPatches,
    },
    wins,
    notableDeploys,
    risks: {
      kevExposure,
      eolHosts,
      identityGaps,
    },
    lookingAhead,
  }
}

// Resolve the report window. When neither startDate nor endDate is given,
// default to the previous full calendar quarter (the "Quarterly" in QBR).
// When only one bound is given, fall back to a 90-day window anchored on it.
function resolveQuarter(
  start?: Date,
  end?: Date,
): { startDate: Date; endDate: Date; periodLabel: string } {
  if (start && end) {
    return {
      startDate: start,
      endDate: end,
      periodLabel: `${start.toISOString().slice(0, 10)} - ${end.toISOString().slice(0, 10)}`,
    }
  }
  if (end && !start) {
    const s = new Date(end.getTime() - 90 * 86_400_000)
    return { startDate: s, endDate: end, periodLabel: `${s.toISOString().slice(0, 10)} - ${end.toISOString().slice(0, 10)}` }
  }
  if (start && !end) {
    const e = new Date(start.getTime() + 90 * 86_400_000)
    return { startDate: start, endDate: e, periodLabel: `${start.toISOString().slice(0, 10)} - ${e.toISOString().slice(0, 10)}` }
  }
  // Neither: previous full quarter.
  const now = new Date()
  const curQ = Math.floor(now.getUTCMonth() / 3)  // 0..3
  // Previous quarter: subtract 1; wrap to Q4 of prior year.
  const prevQ = curQ === 0 ? 3 : curQ - 1
  const prevYear = curQ === 0 ? now.getUTCFullYear() - 1 : now.getUTCFullYear()
  const startMonth = prevQ * 3
  const sd = new Date(Date.UTC(prevYear, startMonth, 1))
  const ed = new Date(Date.UTC(prevYear, startMonth + 3, 0, 23, 59, 59))
  return { startDate: sd, endDate: ed, periodLabel: `Q${prevQ + 1} ${prevYear}` }
}
